name: skymobile
description: SkyMobile

version: 4.0.0+45

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  skyscrapeapi: ^3.0.0+16
  flutter_colorpicker: ^0.3.2
  url_launcher: ^5.2.5
  path_provider: ^1.2.0
  local_auth: ^0.5.2+3
  get_it: ^1.0.3+2
  flutter_reorderable_list: ^0.1.3

cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/CustomizableIcons/iOS/icon.png"
  image_path_android: "assets/CustomizableIcons/Android/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/CustomizableIcons/icon1.png
  - assets/CustomizableIcons/icon2.png
  - assets/CustomizableIcons/icon3.png
  - assets/CustomizableIcons/icon4.png
  - assets/CustomizableIcons/iconchristmas.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900 